//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowTranslator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   このアプリについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC起動時に自動起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoStartWithPC {
            get {
                return ResourceManager.GetString("AutoStartWithPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動翻訳対象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoTargets {
            get {
                return ResourceManager.GetString("AutoTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビルド日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュモジュール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CacheModule {
            get {
                return ResourceManager.GetString("CacheModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CacheParam {
            get {
                return ResourceManager.GetString("CacheParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャーウィンドウ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいバージョンのチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckNewVersion {
            get {
                return ResourceManager.GetString("CheckNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新内容の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckUpdateNotes {
            get {
                return ResourceManager.GetString("CheckUpdateNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デタッチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detach {
            get {
                return ResourceManager.GetString("Detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開発者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMethod {
            get {
                return ResourceManager.GetString("DisplayMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   近いテキストの閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FuzzyMatchThreshold {
            get {
                return ResourceManager.GetString("FuzzyMatchThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全般設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートがあります: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HasUpdate {
            get {
                return ResourceManager.GetString("HasUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   押している間だけ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリ内キャッシュ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InMemoryCache {
            get {
                return ResourceManager.GetString("InMemoryCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいバージョン: {0} のインストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallNewVersion {
            get {
                return ResourceManager.GetString("InstallNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一度翻訳対象に選択したプロセスが起動したときに自動的に翻訳する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsEnableAutoTarget {
            get {
                return ResourceManager.GetString("IsEnableAutoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバーレイ表示をキャプチャー可能にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsEnableCaptureOverlay {
            get {
                return ResourceManager.GetString("IsEnableCaptureOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新バージョンをご利用中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsLatest {
            get {
                return ResourceManager.GetString("IsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローカルファイルキャッシュ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalCache {
            get {
                return ResourceManager.GetString("LocalCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでにWindowTranslatorが起動中です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MutexError {
            get {
                return ResourceManager.GetString("MutexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいバージョン: {0} がリリースされました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoCache {
            get {
                return ResourceManager.GetString("NoCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoTranslateModule {
            get {
                return ResourceManager.GetString("NoTranslateModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認識モジュール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OcrModule {
            get {
                return ResourceManager.GetString("OcrModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細情報の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenChangelogCommand {
            get {
                return ResourceManager.GetString("OpenChangelogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サードパーティーライセンスの確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenThirdPartyLicensesCommand {
            get {
                return ResourceManager.GetString("OpenThirdPartyLicensesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバレイ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Overlay {
            get {
                return ResourceManager.GetString("Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバーレイ切り替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OverlayShortcut {
            get {
                return ResourceManager.GetString("OverlayShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバーレイ表示の切り替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OverlaySwitch {
            get {
                return ResourceManager.GetString("OverlaySwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグイン設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   公開ページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PublishPage {
            get {
                return ResourceManager.GetString("PublishPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全体設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsViewModel {
            get {
                return ResourceManager.GetString("SettingsViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ショートカット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳元(認識)言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳先(表示)言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳対象プロセス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetProcesses {
            get {
                return ResourceManager.GetString("TargetProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ごとの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetSpecificSettings {
            get {
                return ResourceManager.GetString("TargetSpecificSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   押してON/OFFを切り替える に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toggle {
            get {
                return ResourceManager.GetString("Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳モジュール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranslateModule {
            get {
                return ResourceManager.GetString("TranslateModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新バージョンに更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateCommand {
            get {
                return ResourceManager.GetString("UpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateInfo {
            get {
                return ResourceManager.GetString("UpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳結果表示モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewMode {
            get {
                return ResourceManager.GetString("ViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows標準文字認識 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowsMediaOcr {
            get {
                return ResourceManager.GetString("WindowsMediaOcr", resourceCulture);
            }
        }
    }
}
