//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WindowTranslator.Plugin.PLaMoPlugin.Properties;

/// <summary>
/// ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
/// </summary>
// This class was auto-generated by a text template.
// To add or remove a member, edit your .ResX file.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
        
    /// <summary>
    /// このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new CustomResourceManager("WindowTranslator.Plugin.PLaMoPlugin.Properties.Resources", Assembly.GetExecutingAssembly());
        
    /// <summary>
    /// すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    /// 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    /// "コンテキスト長" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string ContextSize => ResourceManager.GetString("ContextSize", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "大きい値ほど長文を翻訳できます。" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string ContextSize_Desc => ResourceManager.GetString("ContextSize_Desc", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "PLaMo モデルのダウンロードに失敗しました。&amp;#13;&amp;#10;{0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string DownloadFailed => ResourceManager.GetString("DownloadFailed", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "PLaMo モデルファイルが見つかりません。" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string ModelFileNotFound => ResourceManager.GetString("ModelFileNotFound", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "PLaMo モデルが初期化されていません。" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string ModelNotInitialized => ResourceManager.GetString("ModelNotInitialized", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "PLaMo" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string PLaMoOptions => ResourceManager.GetString("PLaMoOptions", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "PLaMo翻訳" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string PLaMoTranslator => ResourceManager.GetString("PLaMoTranslator", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "VRAM使用量" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string VRAM => ResourceManager.GetString("VRAM", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "利用するGPUのメモリ量。-1: GPUのみ利用。0: CPUのみ利用。(単位: GB)" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string VRAM_Desc => ResourceManager.GetString("VRAM_Desc", resourceCulture) ?? string.Empty;
}
