//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowTranslator.Plugin.PLaMoPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowTranslator.Plugin.PLaMoPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   PLaMo モデルのパスが設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelPathNotSet {
            get {
                return ResourceManager.GetString("ModelPathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLaMo モデルファイルが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelFileNotFound {
            get {
                return ResourceManager.GetString("ModelFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLaMo モデルが初期化されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelNotInitialized {
            get {
                return ResourceManager.GetString("ModelNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLaMo モデル（.gguf）のパスを指定してください。mmnga/plamo-2-translate-gguf を推奨します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelPath_Desc {
            get {
                return ResourceManager.GetString("ModelPath_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPUに読み込むレイヤー数。0の場合はCPUのみで実行します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GpuLayerCount_Desc {
            get {
                return ResourceManager.GetString("GpuLayerCount_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンテキストサイズ。デフォルトは2048です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextSize_Desc {
            get {
                return ResourceManager.GetString("ContextSize_Desc", resourceCulture);
            }
        }
    }
}
