//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WindowTranslator.Plugin.LLMPlugin.Properties;

/// <summary>
/// ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
/// </summary>
// This class was auto-generated by a text template.
// To add or remove a member, edit your .ResX file.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
        
    /// <summary>
    /// このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new CustomResourceManager("WindowTranslator.Plugin.LLMPlugin.Properties.Resources", Assembly.GetExecutingAssembly());
        
    /// <summary>
    /// すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    /// 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    /// "APIキー" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string ApiKey => ResourceManager.GetString("ApiKey", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "認識補正" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CorrectMode => ResourceManager.GetString("CorrectMode", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "画像認識による補正" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CorrectMode_Image => ResourceManager.GetString("CorrectMode_Image", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "補正なし" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CorrectMode_None => ResourceManager.GetString("CorrectMode_None", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "テキストのみの補正" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CorrectMode_Text => ResourceManager.GetString("CorrectMode_Text", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "補正サンプル" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CorrectSample => ResourceManager.GetString("CorrectSample", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "ローカルLLM接続先" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Endpoint => ResourceManager.GetString("Endpoint", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OpenAIを利用する場合は空" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Endpoint_Desc => ResourceManager.GetString("Endpoint_Desc", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "用語集パス" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string GlossaryPath => ResourceManager.GetString("GlossaryPath", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "翻訳モジュールに「ChatGPT API翻訳」が選択もしくは認識補正が有効化されています。&amp;..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string InvalidOptions => ResourceManager.GetString("InvalidOptions", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "ChatGPT API設定" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string LLMOptions => ResourceManager.GetString("LLMOptions", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "ChatGPT API翻訳" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string LLMTranslator => ResourceManager.GetString("LLMTranslator", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "使用するモデル" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Model => ResourceManager.GetString("Model", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "ChatGPT機能を利用するにはAPIキーの入力が必要です。設定ダイアログからAPIキーを設定してく..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NeedApiKey => ResourceManager.GetString("NeedApiKey", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "LLM機能が初期化されていません。設定ダイアログからLLMオプションを設定してください" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NeedSettings => ResourceManager.GetString("NeedSettings", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "翻訳時に利用する文脈情報" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string TranslateContext => ResourceManager.GetString("TranslateContext", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "補正が完了してから翻訳を行う" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string WaitCorrect => ResourceManager.GetString("WaitCorrect", resourceCulture) ?? string.Empty;
}
