//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowTranslator.Plugin.DeepLTranslatePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowTranslator.Plugin.DeepLTranslatePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DeepLの認可エラーです。利用できないAPIキーが設定されています。APIキーの再作成などお試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthError {
            get {
                return ResourceManager.GetString("AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIキー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthKey {
            get {
                return ResourceManager.GetString("AuthKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用量をチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckUsageCommand {
            get {
                return ResourceManager.GetString("CheckUsageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   用語集パス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GlossaryPath {
            get {
                return ResourceManager.GetString("GlossaryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeepLのAPIキーが設定されていません。設定ダイアログからDeepLのAPIキーを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NeedApiKey {
            get {
                return ResourceManager.GetString("NeedApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeepLの使用量が上限に達しました。現在の使用量: {0} / {1} 文字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuotaExceeded {
            get {
                return ResourceManager.GetString("QuotaExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnknownUsage {
            get {
                return ResourceManager.GetString("UnknownUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
