//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WindowTranslator.Plugin.DeepLTranslatePlugin.Properties;

/// <summary>
/// ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
/// </summary>
// This class was auto-generated by a text template.
// To add or remove a member, edit your .ResX file.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
        
    /// <summary>
    /// このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new CustomResourceManager("WindowTranslator.Plugin.DeepLTranslatePlugin.Properties.Resources", Assembly.GetExecutingAssembly());
        
    /// <summary>
    /// すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    /// 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    /// "DeepLの認可エラーです。利用できないAPIキーが設定されています。APIキーの再作成などお試しく..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string AuthError => ResourceManager.GetString("AuthError", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "APIキー" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string AuthKey => ResourceManager.GetString("AuthKey", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "使用量をチェック" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CheckUsageCommand => ResourceManager.GetString("CheckUsageCommand", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "用語集パス" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string GlossaryPath => ResourceManager.GetString("GlossaryPath", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "DeepLのAPIキーが設定されていません。設定ダイアログからDeepLのAPIキーを設定してくださ..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NeedApiKey => ResourceManager.GetString("NeedApiKey", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "DeepLの使用量が上限に達しました。現在の使用量: {0} / {1} 文字" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string QuotaExceeded => ResourceManager.GetString("QuotaExceeded", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "不明" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string UnknownUsage => ResourceManager.GetString("UnknownUsage", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "使用量" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Usage => ResourceManager.GetString("Usage", resourceCulture) ?? string.Empty;
}
