@deployId = AKfycbxe_E9XjeWckgkkbe9mDoc5GyIQX1CaxFD5bBT6J7Y6JmMrG0U7JaQv-D2Nc0NaXI_APQ

###
GET https://script.google.com/macros/s/{{deployId}}/exec HTTP/1.1
Authorization: Bearer {{wt_oauth_token}}

###
POST https://script.google.com/macros/s/{{deployId}}/exec HTTP/1.1
Authorization: Bearer {{wt_oauth_token}}
Content-Type: application/json

{
  "sourceLanguage": "en",
  "targetLanguage": "ja",
  "texts": ["Hello, World!"]
}
