//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WindowTranslator.Plugin.FoMPlugin.Properties;

/// <summary>
/// ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
/// </summary>
// This class was auto-generated by a text template.
// To add or remove a member, edit your .ResX file.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
        
    /// <summary>
    /// このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new CustomResourceManager("WindowTranslator.Plugin.FoMPlugin.Properties.Resources", Assembly.GetExecutingAssembly());
        
    /// <summary>
    /// すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    /// 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    /// "特定できないテキストを除外" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string ExcludeUnspecifiedText => ResourceManager.GetString("ExcludeUnspecifiedText", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "農場名" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string FarmName => ResourceManager.GetString("FarmName", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "Fields of Mistria専用" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string FoMOptions => ResourceManager.GetString("FoMOptions", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "ゲームに含まれているリソースを利用した補正を利用する" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string IsEnabledCorrect => ResourceManager.GetString("IsEnabledCorrect", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "プレイヤー名" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string PlayerName => ResourceManager.GetString("PlayerName", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "ゲームに含まれている日本語リソースを利用する" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string UseJpn => ResourceManager.GetString("UseJpn", resourceCulture) ?? string.Empty;
}
