//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowTranslator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   基本的なOCRの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasicOcrParam {
            get {
                return ResourceManager.GetString("BasicOcrParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッファサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャーウィンドウ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字サイズずれ閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontSizeThrethold {
            get {
                return ResourceManager.GetString("FontSizeThrethold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   押している間だけ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストのマージを避ける に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsAvoidMergeList {
            get {
                return ResourceManager.GetString("IsAvoidMergeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行間閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LeadingThrethold {
            get {
                return ResourceManager.GetString("LeadingThrethold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マージ閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MergeThrethold {
            get {
                return ResourceManager.GetString("MergeThrethold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバレイ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Overlay {
            get {
                return ResourceManager.GetString("Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認識設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Recognize {
            get {
                return ResourceManager.GetString("Recognize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字間閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpacingThreshold {
            get {
                return ResourceManager.GetString("SpacingThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   押してON/OFFを切り替える に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toggle {
            get {
                return ResourceManager.GetString("Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X位置ずれ閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPosThrethold {
            get {
                return ResourceManager.GetString("XPosThrethold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y位置ずれ閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YPosThrethold {
            get {
                return ResourceManager.GetString("YPosThrethold", resourceCulture);
            }
        }
    }
}
