//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WindowTranslator.Properties;

/// <summary>
/// ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
/// </summary>
// This class was auto-generated by a text template.
// To add or remove a member, edit your .ResX file.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
        
    /// <summary>
    /// このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new CustomResourceManager("WindowTranslator.Properties.Resources", Assembly.GetExecutingAssembly());
        
    /// <summary>
    /// すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    /// 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    /// "基本的なOCRの設定" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string BasicOcrParam => ResourceManager.GetString("BasicOcrParam", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "バッファ機能" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Buffer => ResourceManager.GetString("Buffer", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "バッファサイズ" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string BufferSize => ResourceManager.GetString("BufferSize", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "キャッシュモジュール" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CacheModule => ResourceManager.GetString("CacheModule", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "キャプチャーウィンドウ" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Capture => ResourceManager.GetString("Capture", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "文字サイズずれ閾値" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string FontSizeThrethold => ResourceManager.GetString("FontSizeThrethold", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "押している間だけ" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Hold => ResourceManager.GetString("Hold", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "リストのマージを避ける" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string IsAvoidMergeList => ResourceManager.GetString("IsAvoidMergeList", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "認識ミスの補正" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string IsEnableRecover => ResourceManager.GetString("IsEnableRecover", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "振動の抑制" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string IsSuppressVibe => ResourceManager.GetString("IsSuppressVibe", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "行間閾値" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string LeadingThrethold => ResourceManager.GetString("LeadingThrethold", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "マージ閾値" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string MergeThrethold => ResourceManager.GetString("MergeThrethold", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "その他" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Misc => ResourceManager.GetString("Misc", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "オーバレイ" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Overlay => ResourceManager.GetString("Overlay", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "認識設定" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Recognize => ResourceManager.GetString("Recognize", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "翻訳元言語と翻訳先言語が同一です。異なる言語を指定してください。" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string SameSourceTargetLanguage => ResourceManager.GetString("SameSourceTargetLanguage", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "拡大率" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Scale => ResourceManager.GetString("Scale", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "文字間閾値" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string SpacingThreshold => ResourceManager.GetString("SpacingThreshold", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "押してON/OFFを切り替える" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Toggle => ResourceManager.GetString("Toggle", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "言語設定" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string TranslateLanguage => ResourceManager.GetString("TranslateLanguage", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "翻訳モジュール" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string TranslateModule => ResourceManager.GetString("TranslateModule", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "X位置ずれ閾値" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string XPosThrethold => ResourceManager.GetString("XPosThrethold", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "Y位置ずれ閾値" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string YPosThrethold => ResourceManager.GetString("YPosThrethold", resourceCulture) ?? string.Empty;
}
