//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowTranslator.Plugin.OneOcrPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowTranslator.Plugin.OneOcrPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   中断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AbortButton {
            get {
                return ResourceManager.GetString("AbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「切り取り領域とスケッチ」の更新を確認中...
        ///
        ///Microsoft Storeで更新を完了してください。
        ///更新が完了すると自動的に次に進みます。
        ///
        ///&gt; #### 更新が完了しない場合
        ///&gt; お手数ですが、Microsoft Storeで「更新とダウンロード」から更新を完了してから再度お試しください。
        ///&gt; [更新とダウンロードを開く](ms-windows-store://downloadsandupdates) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckingUpdateContent {
            get {
                return ResourceManager.GetString("CheckingUpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新確認中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckingUpdateTitle {
            get {
                return ResourceManager.GetString("CheckingUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OneOcrのDLLのコピーに失敗しました。{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyFaild {
            get {
                return ResourceManager.GetString("CopyFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCRパイプラインの作成に失敗しました。エラーコード: {0}
        ///「切り取り領域とスケッチ(SnippingTool)」もしくは「Microsoft フォト」アプリの更新をお試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreatePipelineFaild {
            get {
                return ResourceManager.GetString("CreatePipelineFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCRプロセスオプションの作成に失敗しました。エラーコード: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateProcessOptionsFaild {
            get {
                return ResourceManager.GetString("CreateProcessOptionsFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoNotUpdateButton {
            get {
                return ResourceManager.GetString("DoNotUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCR行の境界ボックスの取得に失敗しました。行番号: {0}, エラーコード: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetLineBoundingBoxFaild {
            get {
                return ResourceManager.GetString("GetLineBoundingBoxFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCR行のテキスト内容の取得に失敗しました。行番号: {0}, エラーコード: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetLineContentFaild {
            get {
                return ResourceManager.GetString("GetLineContentFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCR行数の取得に失敗しました。エラーコード: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetLineCountFaild {
            get {
                return ResourceManager.GetString("GetLineCountFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCR行の取得に失敗しました。行番号: {0}, エラーコード: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetLineFaild {
            get {
                return ResourceManager.GetString("GetLineFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCRの初期化オプション作成に失敗しました。エラーコード: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitFaild {
            get {
                return ResourceManager.GetString("InitFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依存モジュールが見つかりません。この環境では利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundModule {
            get {
                return ResourceManager.GetString("NotFoundModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依存モジュールが見つかりません。この環境では利用できません。{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundModuleWithVersion {
            get {
                return ResourceManager.GetString("NotFoundModuleWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新Windows文字認識(ベータ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OneOcr {
            get {
                return ResourceManager.GetString("OneOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Storeを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenStoreButton {
            get {
                return ResourceManager.GetString("OpenStoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCRパイプラインの実行に失敗しました。エラーコード: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunPipelineFaild {
            get {
                return ResourceManager.GetString("RunPipelineFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCRモデル遅延読み込み設定に失敗しました。エラーコード: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetLazyLoadFaild {
            get {
                return ResourceManager.GetString("SetLazyLoadFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCR最大認識行数の設定に失敗しました。エラーコード: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetMaxRecognitionLineCountFaild {
            get {
                return ResourceManager.GetString("SetMaxRecognitionLineCountFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OneOcrを利用するには「切り取り領域とスケッチ」アプリの更新が必要です。
        ///
        ///Microsoft Storeを開いて更新を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateDialogContent {
            get {
                return ResourceManager.GetString("UpdateDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り領域とスケッチの更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateDialogTitle {
            get {
                return ResourceManager.GetString("UpdateDialogTitle", resourceCulture);
            }
        }
    }
}
