//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WindowTranslator.Plugin.OneOcrPlugin.Properties;

/// <summary>
/// ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
/// </summary>
// This class was auto-generated by a text template.
// To add or remove a member, edit your .ResX file.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
        
    /// <summary>
    /// このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new CustomResourceManager("WindowTranslator.Plugin.OneOcrPlugin.Properties.Resources", Assembly.GetExecutingAssembly());
        
    /// <summary>
    /// すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    /// 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    /// "中断" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string AbortButton => ResourceManager.GetString("AbortButton", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "「切り取り領域とスケッチ」の更新を確認中...&amp;#13;&amp;#10;&amp;#13;..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CheckingUpdateContent => ResourceManager.GetString("CheckingUpdateContent", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "更新確認中..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CheckingUpdateTitle => ResourceManager.GetString("CheckingUpdateTitle", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OneOcrのDLLのコピーに失敗しました。{0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CopyFaild => ResourceManager.GetString("CopyFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCRパイプラインの作成に失敗しました。エラーコード: {0}&amp;#13;&amp;#10;「..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CreatePipelineFaild => ResourceManager.GetString("CreatePipelineFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCRプロセスオプションの作成に失敗しました。エラーコード: {0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string CreateProcessOptionsFaild => ResourceManager.GetString("CreateProcessOptionsFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "更新しない" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string DoNotUpdateButton => ResourceManager.GetString("DoNotUpdateButton", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCR行の境界ボックスの取得に失敗しました。行番号: {0}, エラーコード: {1}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string GetLineBoundingBoxFaild => ResourceManager.GetString("GetLineBoundingBoxFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCR行のテキスト内容の取得に失敗しました。行番号: {0}, エラーコード: {1}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string GetLineContentFaild => ResourceManager.GetString("GetLineContentFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCR行数の取得に失敗しました。エラーコード: {0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string GetLineCountFaild => ResourceManager.GetString("GetLineCountFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCR行の取得に失敗しました。行番号: {0}, エラーコード: {1}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string GetLineFaild => ResourceManager.GetString("GetLineFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCRの初期化オプション作成に失敗しました。エラーコード: {0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string InitFaild => ResourceManager.GetString("InitFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "依存モジュールが見つかりません。この環境では利用できません。" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NotFoundModule => ResourceManager.GetString("NotFoundModule", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "依存モジュールが見つかりません。この環境では利用できません。{0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NotFoundModuleWithVersion => ResourceManager.GetString("NotFoundModuleWithVersion", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "新Windows文字認識(ベータ)" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string OneOcr => ResourceManager.GetString("OneOcr", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "Storeを開く" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string OpenStoreButton => ResourceManager.GetString("OpenStoreButton", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCRパイプラインの実行に失敗しました。エラーコード: {0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string RunPipelineFaild => ResourceManager.GetString("RunPipelineFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCRモデル遅延読み込み設定に失敗しました。エラーコード: {0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string SetLazyLoadFaild => ResourceManager.GetString("SetLazyLoadFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OCR最大認識行数の設定に失敗しました。エラーコード: {0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string SetMaxRecognitionLineCountFaild => ResourceManager.GetString("SetMaxRecognitionLineCountFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "OneOcrを利用するには「切り取り領域とスケッチ」アプリの更新が必要です。&amp;#13;&am..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string UpdateDialogContent => ResourceManager.GetString("UpdateDialogContent", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "切り取り領域とスケッチの更新" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string UpdateDialogTitle => ResourceManager.GetString("UpdateDialogTitle", resourceCulture) ?? string.Empty;
}
