//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowTranslator.Plugin.BergamotTranslatorPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowTranslator.Plugin.BergamotTranslatorPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   モデルファイルのダウンロードに失敗しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadFaild {
            get {
                return ResourceManager.GetString("DownloadFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bergamot モデルが存在しないため、翻訳できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelNotFound {
            get {
                return ResourceManager.GetString("ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご利用のPCではBergamotを利用できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotAvailableArch {
            get {
                return ResourceManager.GetString("NotAvailableArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}から{1}への翻訳可能なモデルデータは見つかりませんでした。この言語ペアでの翻訳は利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundCompatModel {
            get {
                return ResourceManager.GetString("NotFoundCompatModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}から翻訳できるモデルデータが見つかりませんでした。この言語の翻訳は利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundFromModel {
            get {
                return ResourceManager.GetString("NotFoundFromModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}へ翻訳できるモデルデータが見つかりませんでした。この言語の翻訳は利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundToModel {
            get {
                return ResourceManager.GetString("NotFoundToModel", resourceCulture);
            }
        }
    }
}
