//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WindowTranslator.Plugin.BergamotTranslatorPlugin.Properties;

/// <summary>
/// ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
/// </summary>
// This class was auto-generated by a text template.
// To add or remove a member, edit your .ResX file.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
        
    /// <summary>
    /// このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new CustomResourceManager("WindowTranslator.Plugin.BergamotTranslatorPlugin.Properties.Resources", Assembly.GetExecutingAssembly());
        
    /// <summary>
    /// すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    /// 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    /// "モデルファイルのダウンロードに失敗しました。&amp;#13;&amp;#10;{0}" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string DownloadFaild => ResourceManager.GetString("DownloadFaild", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "Bergamot モデルが存在しないため、翻訳できません。" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string ModelNotFound => ResourceManager.GetString("ModelNotFound", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "ご利用のPCではBergamotを利用できません" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NotAvailableArch => ResourceManager.GetString("NotAvailableArch", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "{0}から{1}への翻訳可能なモデルデータは見つかりませんでした。この言語ペアでの翻訳は利用できませ..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NotFoundCompatModel => ResourceManager.GetString("NotFoundCompatModel", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "{0}から翻訳できるモデルデータが見つかりませんでした。この言語の翻訳は利用できません。" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NotFoundFromModel => ResourceManager.GetString("NotFoundFromModel", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "{0}へ翻訳できるモデルデータが見つかりませんでした。この言語の翻訳は利用できません。" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NotFoundToModel => ResourceManager.GetString("NotFoundToModel", resourceCulture) ?? string.Empty;
}
