name: .NET Core Package

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: "6.x"
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v4.1.0
      - run: |
          dotnet pack WindowTranslator.Abstractions -c Release -o pack `
            -p:Version=${{ steps.gitversion.outputs.fullSemVer }} `
            -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} `
            -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} `
            -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
          dotnet nuget push pack\*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
