name: .NET Core Package

on:
  pull_request:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/cache@v6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: "6.x"
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v4.7.0
      - uses: Jimver/cuda-toolkit@v0.2.30
        with:
          cuda: '12.9.0'
      - run: |
          dotnet msbuild Plugins\WindowTranslator.Plugins.proj -target:Pack `
            -p:Configuration=Release `
            -p:PackageOutputPath="$PWD\pack" `
            -p:Version=${{ steps.gitversion.outputs.fullSemVer }} `
            -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} `
            -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} `
            -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }} `
            -p:DecryptKey="${{ secrets.WINDOWTRANSLATOR_DECRYPTKEY }}"
      - name: NuGet login
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        id: nuget_login
        uses: NuGet/login@v1
        with:
          user: Freesia
      - name: NuGet push
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: dotnet nuget push pack\*.nupkg --api-key ${{ steps.nuget_login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
