//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WindowTranslator.Plugin.TesseractOCRPlugin.Properties;

/// <summary>
/// ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
/// </summary>
// This class was auto-generated by a text template.
// To add or remove a member, edit your .ResX file.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
        
    /// <summary>
    /// このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new CustomResourceManager("WindowTranslator.Plugin.TesseractOCRPlugin.Properties.Resources", Assembly.GetExecutingAssembly());
        
    /// <summary>
    /// すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    /// 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    /// "キャンセル" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "TesseractOcrを利用するにはVisual C++ Redistributableが必要です..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string ConfirmInstall => ResourceManager.GetString("ConfirmInstall", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "インストール" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string Install => ResourceManager.GetString("Install", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "Visual C++ Redistributableをインストール中...&amp;#13;&amp..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string InstallingMessage => ResourceManager.GetString("InstallingMessage", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "Visual C++ Redistributableのインストール中..." に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string InstallingTitle => ResourceManager.GetString("InstallingTitle", resourceCulture) ?? string.Empty;

    /// <summary>
    /// "Visual C++ Redistributableがインストールされていません" に類似しているローカライズされた文字列を検索します。
    /// </summary>
    public static string NotInstalledVcRedist => ResourceManager.GetString("NotInstalledVcRedist", resourceCulture) ?? string.Empty;
}
