//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowTranslator.Plugin.TesseractOCRPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowTranslator.Plugin.TesseractOCRPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TesseractOcrを利用するにはVisual C++ Redistributableが必要です。  
        ///インストールを行いますか？
        ///
        ///&gt; #### オプション
        ///&gt; [手動でインストールする](https://aka.ms/vs/17/release/vc_redist.x64.exe)  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmInstall {
            get {
                return ResourceManager.GetString("ConfirmInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual C++ Redistributableをインストール中...
        ///数分かかる場合があります。
        ///
        ///&gt; #### インストールが完了しない場合
        ///&gt; お手数ですが、手動でのインストールを試してください。
        ///&gt; [手動でインストールする](https://aka.ms/vs/17/release/vc_redist.x64.exe) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallingMessage {
            get {
                return ResourceManager.GetString("InstallingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual C++ Redistributableのインストール中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallingTitle {
            get {
                return ResourceManager.GetString("InstallingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual C++ Redistributableがインストールされていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotInstalledVcRedist {
            get {
                return ResourceManager.GetString("NotInstalledVcRedist", resourceCulture);
            }
        }
    }
}
